spring.application.name=gym-movements-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_movements
spring.datasource.username=postgres
spring.datasource.password=NathanC#6
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
